<!DOCTYPE html>
<html lang="en">
<head>
  <title>HL - Deadlines Overview</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="HL REPRO">
  <style type="text/css">
html, body, #container {
  width: 100vw;
  height: 100vh;
  padding:0;
  margin:0;
  font-family: Arial, Helvetica, sans-serif;
}
#container {
  /*background: linear-gradient(0deg, #2f809d 0%, #3fa1c6 100%);*/
  background: linear-gradient(-45deg, #8CD523, #23a6d5);
	background-size: 200% 200%;
	animation: gradient 180s ease infinite;
  display: flex;
  flex-direction: column;
  align-items: stretch;
}
@keyframes gradient {
	0% {
		background-position: 0% 50%;
	}
	50% {
		background-position: 100% 50%;
	}
	100% {
		background-position: 0% 50%;
	}
}
#forbidden {
    flex: 1 1 100%;
    text-align:center;
    font-size: 7em;
    line-height:100vh;
    color:#fff;
    mix-blend-mode: overlay;
}
  </style>
</head>
<body>
<div id="container">
  <div id="forbidden">FORBIDDEN</div>
  </div>
</div>
<script type="text/javascript">


</script>
</body>
</html>