Content of HL Deadlines plugin
<h4> Test mode 1</h4>
<p> In this mode, all the logic is ran as normal, except :
<ul style="list-style-type: disc;padding-left:3em;">
    <li>only configuration of status <?= $this->testStatusLabel ?> (<?= $this->testStatusId ?>) will be used</li>
    <li>No email will be sent</li>
    <li>You (<?= Kbx_Users::getLogin(Kbx_Users::getCurrentUserId()) ?>) will be the only recipient of notifications</li>
</ul>
</p>

<h4> Test mode 2</h4>
<p> In this mode, all the logic is ran as normal, except :
<ul style="list-style-type: disc;padding-left:3em;">
    <li>You (<?= Kbx_Users::getLogin(Kbx_Users::getCurrentUserId()) ?>) will be the only recipient of notifications / emails</li>
</ul>
</p>
<script type="text/javascript">
$('#<?= $this->dialogId ?>').dialog('option','buttons',{
    "Close" : function(){
        $('#<?= $this->dialogId?>').dialog('destroy');
    },
    "Refresh" : function(){
        openDialog('/plugin/index/plugin/HlDeadlines',500,300,{execute : 'index'}, '', false, '<?= $this->dialogId?>');
    }
}).dialog('option', 'width', 600)
.dialog('option', 'height', 600)
.dialog('option','position','center');
</script>