<h4 style="margin-top:2em;"> Test mode 1</h4>
<p> In this mode, all the logic is ran as normal, except :
<ul style="list-style-type: disc;padding-left:3em;">
    <li>only configurations of status <?= $this->testStatusLabel ?> (<?= $this->testStatusId ?>) will be used</li>
    <li>only projects of status <?= $this->projectsTestStatusLabel ?> (<?= $this->projectsTestStatusId ?>) will be used</li>
    <li>You (<?= Kbx_Users::getLogin(Kbx_Users::getCurrentUserId()) ?>) will be the only recipient of notifications / emails</li>
</ul>
<button class="bouton ui-corner-all" style="margin-top:1em;" onClick="openDialog('/plugin/index/plugin/HlDeadlines',500,300,{execute : 'runTest', test_mode: '1'}, '', false, '<?= $this->dialogId?>');">
    <span class="font_icon icon-arrow-right"/> RUN TEST MODE 1
</button>
</p>

<h4 style="margin-top:2em;"> Test mode 2</h4>
<p> In this mode, all the logic is ran as normal, except :
<ul style="list-style-type: disc;padding-left:3em;">
    <li>You (<?= Kbx_Users::getLogin(Kbx_Users::getCurrentUserId()) ?>) will be the only recipient of notifications / emails</li>
</ul>
<button class="bouton ui-corner-all" style="margin-top:1em;" onClick="openDialog('/plugin/index/plugin/HlDeadlines',500,300,{execute : 'runTest', test_mode: '2'}, '', false, '<?= $this->dialogId?>');">
    <span class="font_icon icon-arrow-right"/> RUN TEST MODE 2
</button>
</p>

<h4 style="margin-top:2em;"> Run </h4>
<p> In this mode, all the logic is ran as normal
<br/>
<button class="bouton ui-corner-all" style="margin-top:1em;">
    <span class="font_icon icon-arrow-right"/> RUN
</button>
</p>

<h4 style="margin-top:2em;"> Overview screen</h4>
<p>
    <a href="<?= $this->overviewUrl ?>" target="_blank"><?= $this->overviewUrl ?></a><br/>
    <br/>
    <a href="<?= $this->overviewUrl ?>/fake/1" target="_blank">Click here for overview screen with fake datas</a>
</p>
<script type="text/javascript">
$('#<?= $this->dialogId ?>').dialog('option','buttons',{
    "Close" : function(){
        $('#<?= $this->dialogId?>').dialog('destroy');
    },
    "Refresh" : function(){
        openDialog('/plugin/index/plugin/HlDeadlines',500,300,{execute : 'index'}, '', false, '<?= $this->dialogId?>');
    }
}).dialog('option', 'width', 600)
.dialog('option', 'height', 600)
.dialog('option','position','center');
</script>